// Auto generated by statefile.py
#pragma once
const char *const STATE_FILE_JSON = R"json({  "brightness": 30,  "text": [    {      "type": 0,      "font": 0,      "x": 0,      "y": 0,      "enabled": true,      "color": 16777215,      "body": ""    }  ],  "pattern": 2,  "speed": 1.0})json";